version: "3"
networks:
  default:
    external:
      name: minorgordon.net
services:
  generic-gui:
    build:
      context: gui/generic
    container_name: generic-gui
  generic-service:
    build:
      context: .
      dockerfile: service/generic/Dockerfile
    container_name: generic-service
    stdin_open: true
  fuseki:
    build:
      context: fuseki
    container_name: fuseki
    ports:
      - 127.0.0.1:3030:3030
