version: 2
jobs:
  cms-gui:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: gui-core-dependency-cache-v1-{{ checksum "cms/gui/core/package.json" }}
      - run:
          command: cd cms/gui/core && npm install
      - save_cache:
          key: gui-core-dependency-cache-v1-{{ checksum "cms/gui/core/package.json" }}
          paths:
            - ./cms/gui/core/node_modules
      - run:
          command: cd cms/gui/core && npm run build
  cms-service:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-v1
      - run:
          name: Create test-results directory
          command: mkdir -p test-results/scala
      - run:
          name: Test service/core
          command: |
            cd cms/service/core
            sbt clean update package test
            cp target/test-reports/*.xml ~/project/test-results/scala
      - save_cache:
          key: sbt-cache-v1
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
      - store_test_results:
          path: test-results
workflows:
  version: 2
  build-and-test-cms:
    jobs:
      - cms-gui
      - cms-service
