version: 2
jobs:
  gui:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: gui-generic-dependency-cache-v1-{{ checksum "gui/generic/package.json" }}
      - run:
          command: cd gui/generic && npm install
      - save_cache:
          key: gui-generic-dependency-cache-v1-{{ checksum "gui/generic/package.json" }}
          paths:
            - ./gui/generic/node_modules
      - run:
          command: cd gui/generic && npm run build
  service:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-v1
      - run:
          name: Create test-results directory
          command: mkdir -p test-results/scala
      - run:
          name: Test
          command: |
            sbt clean update package test
            cp service/generic/target/test-reports/*.xml ~/project/test-results/scala
            cp service/lib/target/test-reports/*.xml ~/project/test-results/scala
      - save_cache:
          key: sbt-cache-v1
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
      - store_test_results:
          path: test-results
workflows:
  version: 2
  build:
    jobs:
      - gui
      - service
