version: 2
jobs:
  scala:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-v1
      - run:
          name: Create test-results directory
          command: mkdir -p test-results/scala
      - run:
          name: Test
          command: |
            sbt clean update package test
            cp app/generic/target/test-reports/*.xml ~/project/test-results/scala
#            cp lib/scala/generic/target/test-reports/*.xml ~/project/test-results/scala
      - save_cache:
          key: sbt-cache-v1
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
      - store_test_results:
          path: test-results
  ts:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: gui-dependency-cache-v1-{{ checksum "package.json" }}-{{ checksum "app/generic/gui/package.json" }}-{{ checksum "lib/ts/generic/package.json" }}
      - run:
          command: |
            npm install
            npm run lerna:bootstrap
      - save_cache:
          key: gui-dependency-cache-v1-{{ checksum "package.json" }}-{{ checksum "app/generic/gui/package.json" }}-{{ checksum "lib/ts/generic/package.json" }}
          paths:
            - ./node_modules
            - ./lib/ts/generic/node_modules
      - run:
          command: |
            cd lib/ts/generic
            npm run build
            cd ../../../app/generic/gui
            npm run build
workflows:
  version: 2
  build:
    jobs:
      - scala
      - ts
