version: 2.1
jobs:
  scala:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:11
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - restore_cache:
          key: sbt-cache-v1
      - run:
          name: Set up GPG and sbt-pgp
          command: |
            # See https://discuss.circleci.com/t/gpg-keys-as-environment-variables/28641/3
            echo -e "$OSSRH_GPG_KEY" | gpg --import
            mkdir -p ~/.sbt/gpg
            gpg -a --export-secret-keys >~/.sbt/gpg/secring.asc
            mkdir -p ~/.sbt/1.0/plugins
            echo 'addSbtPlugin("com.jsuereth" % "sbt-pgp" % "2.0.0")' >~/.sbt/1.0/plugins/pgp.sbt
      - run:
          name: Write OSSRH credentials
          command: |
            mkdir -p ~/.sbt/1.0
            echo "credentials += Credentials(\"Sonatype Nexus Repository Manager\", \"oss.sonatype.org\", \"$SONATYPE_USERNAME\", \"$SONATYPE_PASSWORD\")" >>~/.sbt/1.0/sonatype.sbt
            echo "pgpPassphrase := Some(Array[Char]())" >>~/.sbt/1.0/sonatype.sbt
      - run:
          name: Create test-results directory
          command: mkdir -p test-results/scala
      - run:
          name: Build and test
          command: |
            sbt clean update package test
            cp app/generic/target/test-reports/*.xml ~/project/test-results/scala
      #            cp lib/scala/generic/target/test-reports/*.xml ~/project/test-results/scala
      - store_test_results:
          path: test-results
      - run:
          name: Build a dist package with the GUI for integration testing
          command: |
            echo -e "auth0.clientSecret=$AUTH0_CLIENT_SECRET\nauth0.clientId=$AUTH0_CLIENT_ID\nauth0.domain=$AUTH0_DOMAIN\nauth0.callbackURL=\"http://localhost:9000/api/auth0/loginCallback\"\nauth0.audience=\"\"" >app/generic/conf/application.auth0.conf
            cp -p -R /tmp/workspace/dist/generic-gui app/generic/public
            sbt "project genericApp" playUpdateSecret dist
            cd app/generic/target/universal
            unzip generic-app*.zip
            rm generic-app*.zip
            mkdir ~/dist
            mv generic-app-*-SNAPSHOT ~/dist/generic-app
      - persist_to_workspace:
          root: ~/
          paths:
            - dist/generic-app
      - run:
          name: Publish (master branch only)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sbt publishSigned
            fi
      - run:
          name: Clear secret data before caching
          command: |
            rm -fr ~/.sbt/gpg
            rm ~/.sbt/1.0/sonatype.sbt
      - save_cache:
          key: sbt-cache-v1
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  ts:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: ts-dependency-cache-v1-{{ checksum "package.json" }}-{{ checksum "app/generic/gui/package.json" }}-{{ checksum "lib/ts/base/package.json" }}
      - run:
          command: |
            npm install
            npm run lerna:bootstrap
      - save_cache:
          key: ts-dependency-cache-v1-{{ checksum "package.json" }}-{{ checksum "app/generic/gui/package.json" }}-{{ checksum "lib/ts/base/package.json" }}
          paths:
            - ./node_modules
            - ./lib/ts/base/node_modules
      - run:
          name: Build
          command: |
            cd lib/ts/base
            npm run build
            cd ../../../app/generic/gui
            npm run build
            mkdir ~/dist
            mv dist ~/dist/generic-gui
      - persist_to_workspace:
          root: ~/
          paths:
            - dist/generic-gui
orbs:
  cypress: cypress-io/cypress@1
workflows:
  version: 2
  build:
    jobs:
      - ts
      - scala:
          requires:
            - ts
      - cypress/install:
          requires:
            - scala
            - ts
          working_directory: app/generic/test/integration
      - cypress/run:
          attach-workspace: true
          post-steps:
            - store_test_results:
                path: cypress/results
          pre-steps:
            - run: 'cp .circleci/cypress.json app/generic/test/integration'
          requires:
            - cypress/install
          start: |
            apt-get update && apt-get install -y default-jre
            cd ~/dist/generic-app
            bin/generic-app
          wait-on: 'http-get://localhost:9000/index.html'
          working_directory: app/generic/test/integration
